### PR TITLE
Add Armenia + flag

### PR DESCRIPTION
**Pull request by texeltexel2009**
Added Armenian names, surnames and the flag image file. Please let me know if I missed something so I can add it.

### CODE REVIEW

**Comment by thm** [comment]
Thanks a lot for the contribution!

**Comment by texeltexel2009** [comment]
I see you don't have catalán. Catalonia is still part of Spain but the names are different. Can I still add it?

**Comment by thm** [comment]
@texeltexel2009 sure thing! I've been thinking of changing 'country' to 'region' everywhere in the code, to avoid the controversy around the subject. I'll get that out of the way over the weekend

**Comment by thm** [comment]
Easier than expected, all done! Commit for reference: https://github.com/thm/uinames/commit/b16c1da390544972fe07302b5f77f9af81d9eb8d

**Pull request merged**
